'use strict';
const express = require('express');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const { AppError } = require('../middleware/errorHandler');
const log = require('../utils/logger');
const ffmpegPath = require('../utils/ffmpeg');

const router = express.Router();
const execFileAsync = promisify(execFile);

const INSTAGRAM_URL_RE = /https?:\/\/(www\.)?instagram\.com\/(p|reel|reels|tv|stories)\/[A-Za-z0-9_\-]+/i;
const TIKTOK_URL_RE = /https?:\/\/(www\.|vm\.|m\.|vt\.)?tiktok\.com\/([A-Za-z0-9_@\-\.\/]+)/i;
const X_URL_RE = /https?:\/\/(www\.)?(twitter|x)\.com\/[A-Za-z0-9_]+\/status\/\d+/i;
const MAX_FRAMES = 60;
const MAX_INTERVAL_MS = 5000;
const MIN_INTERVAL_MS = 50;

const IG_COOKIES_PATH = path.join(os.homedir(), '.kyros-ig-cookies.txt');
const TT_COOKIES_PATH = path.join(os.homedir(), '.kyros-tt-cookies.txt');
const X_COOKIES_PATH = path.join(os.homedir(), '.kyros-x-cookies.txt');

function detectPlatform(url) {
  if (url && INSTAGRAM_URL_RE.test(url)) return 'instagram';
  if (url && TIKTOK_URL_RE.test(url)) return 'tiktok';
  if (url && X_URL_RE.test(url)) return 'x';
  return null;
}

function getTempDir() {
  const dir = path.join(os.tmpdir(), 'kyros-ig-frames');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function cleanupDir(dir) {
  try {
    if (dir && fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
  } catch {}
}

// Find yt-dlp on PATH or common install locations
function findYtDlp() {
  const candidates = [
    path.join(process.env.LOCALAPPDATA || '', 'Programs', 'Python', 'Python310', 'Scripts', 'yt-dlp.exe'),
    path.join(process.env.LOCALAPPDATA || '', 'Programs', 'Python', 'Python311', 'Scripts', 'yt-dlp.exe'),
    path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'WinGet', 'Links', 'yt-dlp.exe'),
    'yt-dlp',
  ];
  for (const c of candidates) {
    try {
      if (fs.existsSync(c)) return c;
    } catch {}
  }
  return 'yt-dlp';
}

function findGalleryDl() {
  const candidates = [
    path.join(process.env.LOCALAPPDATA || '', 'Programs', 'Python', 'Python310', 'Scripts', 'gallery-dl.exe'),
    path.join(process.env.LOCALAPPDATA || '', 'Programs', 'Python', 'Python311', 'Scripts', 'gallery-dl.exe'),
    path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'WinGet', 'Links', 'gallery-dl.exe'),
    'gallery-dl',
  ];
  for (const c of candidates) {
    try {
      if (fs.existsSync(c)) return c;
    } catch {}
  }
  return 'gallery-dl';
}

const SCRAPER_PROXY_PATH = path.join(os.homedir(), '.kyros-scraper-proxy.txt');

// Optional proxy for the scraper (keeps your real IP out of the scraping path).
// Set via env KYROS_SCRAPER_PROXY or the save-proxy endpoint (file).
function resolveScraperProxy() {
  const env = process.env.KYROS_SCRAPER_PROXY || process.env.SCRAPER_PROXY;
  if (env && env.trim()) return env.trim();
  try {
    if (fs.existsSync(SCRAPER_PROXY_PATH)) {
      const v = fs.readFileSync(SCRAPER_PROXY_PATH, 'utf8').trim();
      if (v) return v;
    }
  } catch {}
  return '';
}

// Convert a browser-extension JSON cookie export (Cookie-Editor etc.) to Netscape.
function jsonCookiesToNetscape(jsonStr) {
  let arr;
  try { arr = JSON.parse(jsonStr); } catch { return null; }
  if (!Array.isArray(arr) || arr.length === 0) return null;
  const lines = ['# Netscape HTTP Cookie File', '# Generated by Kyros Studio', ''];
  for (const c of arr) {
    if (!c || !c.name || typeof c.value === 'undefined') continue;
    const domain = c.domain || '.instagram.com';
    const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const domField = c.httpOnly ? `#HttpOnly_${domain}` : domain;
    const cpath = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const exp = c.session ? 0 : (Math.floor(Number(c.expirationDate || c.expires || 0)) || 0);
    lines.push([domField, includeSub, cpath, secure, String(exp), c.name, c.value].join('\t'));
  }
  return lines.length > 3 ? lines.join('\n') + '\n' : null;
}

// Best-effort yt-dlp + gallery-dl self-update on server start (IG/TikTok change their
// internals often and break these tools; keeping them current avoids silent failures).
// Throttled to once per 24h so it doesn't slow every restart.
const YTDLP_UPDATE_STAMP = path.join(os.homedir(), '.kyros-ytdlp-updated.txt');
let _ytDlpUpdated = false;

function _shouldUpdateYtDlp() {
  try {
    if (fs.existsSync(YTDLP_UPDATE_STAMP)) {
      const last = Number(fs.readFileSync(YTDLP_UPDATE_STAMP, 'utf8').trim()) || 0;
      if (Date.now() - last < 24 * 60 * 60 * 1000) return false;
    }
  } catch {}
  return true;
}

function runYtDlpSelfUpdate() {
  if (_ytDlpUpdated) return;
  _ytDlpUpdated = true;
  if (!_shouldUpdateYtDlp()) return;
  try { fs.writeFileSync(YTDLP_UPDATE_STAMP, String(Date.now()), 'utf8'); } catch {}

  const ytDlp = findYtDlp();
  // pip-installed yt-dlp can't self-update via -U; update via the matching Python's pip.
  const pipUpdate = () => {
    let python = 'python';
    const m = ytDlp.match(/^(.*)[\\/]Scripts[\\/]yt-dlp\.exe$/i);
    if (m) python = path.join(m[1], 'python.exe');
    execFile(python, ['-m', 'pip', 'install', '--upgrade', 'yt-dlp', 'gallery-dl'], { timeout: 180_000 }, (err, stdout) => {
      if (err) log.warn('yt_dlp_pip_update_failed', { error: (err.stderr || err.message || '').slice(0, 200) });
      else log.info('yt_dlp_pip_update_ok', { out: String(stdout || '').trim().slice(-160) });
    });
  };

  try {
    execFile(ytDlp, ['-U'], { timeout: 90_000 }, (err, stdout) => {
      if (err) {
        const msg = err.stderr || err.message || '';
        if (/pip|wheel|pypi/i.test(msg)) { pipUpdate(); return; }
        log.warn('yt_dlp_selfupdate_failed', { error: msg.slice(0, 200) });
      } else {
        log.info('yt_dlp_selfupdate_ok', { out: String(stdout || '').trim().slice(0, 160) });
      }
    });
  } catch (e) {
    log.warn('yt_dlp_selfupdate_error', { error: e.message });
  }
}

// Apify fallback (Instagram only): when the local tools can't download a post (bad/expired
// cookies, private, blocked IP), fetch its image(s) via Apify — which uses its own token,
// so it can rescue what cookies can't. Writes images into sessionDir; returns true if any saved.
async function tryApifyImageFallback(url, sessionDir) {
  const apiKeyManager = require('../services/apiKeyManager');
  let apifyToken = '';
  try { apifyToken = apiKeyManager.getApifyKey(); } catch {}
  if (!apifyToken) return false;
  const { runPostActor, normalizePostsFromItems } = require('../services/postClone/apifyFetcher');
  const axios = require('axios');
  const items = await runPostActor({ url, limit: 1, apifyToken });
  const raw = Array.isArray(items) ? items[0] : null;
  // NEVER save a video's cover thumbnail — Instagram bakes a ▶ play button into reel/clip
  // covers. If this post is a video (reel/clip) and has no genuine image slides, bail so it
  // fails cleanly instead of importing a ▶ frame.
  const rawType = String(raw?.type || raw?.productType || '').toLowerCase();
  const isVideoPost = !!raw?.videoUrl || /video|clip/.test(rawType);
  const childImageUrls = Array.isArray(raw?.childPosts)
    ? raw.childPosts.filter(c => !c.videoUrl && c.displayUrl).map(c => c.displayUrl)
    : [];
  if (isVideoPost && childImageUrls.length === 0) {
    log.info('media_frames_apify_fallback_skipped_video', { url });
    return false;
  }
  let imageUrls;
  if (rawType.includes('sidecar') && childImageUrls.length) {
    imageUrls = childImageUrls; // carousel: only the genuine (non-video) image slides
  } else {
    const posts = normalizePostsFromItems(items || []);
    const post = Array.isArray(posts) ? posts[0] : null;
    imageUrls = post && Array.isArray(post.imageUrls) ? post.imageUrls.filter(Boolean) : [];
  }
  if (imageUrls.length === 0) return false;
  let saved = 0;
  for (let i = 0; i < imageUrls.length && i < 12; i += 1) {
    try {
      const resp = await axios.get(imageUrls[i], { responseType: 'arraybuffer', timeout: 30_000 });
      const ct = String(resp.headers['content-type'] || '');
      const ext = ct.includes('png') ? '.png' : ct.includes('webp') ? '.webp' : '.jpg';
      fs.writeFileSync(path.join(sessionDir, `apify_${String(i).padStart(3, '0')}${ext}`), Buffer.from(resp.data));
      saved += 1;
    } catch { /* skip this image */ }
  }
  return saved > 0;
}

// GET /api/instagram-frames/cookies-status
// Returns whether cookies.txt are saved and their basic info
router.get('/cookies-status', (req, res) => {
  const igExists = fs.existsSync(IG_COOKIES_PATH);
  const ttExists = fs.existsSync(TT_COOKIES_PATH);
  const xExists = fs.existsSync(X_COOKIES_PATH);
  
  let igInfo = { hasCookies: false };
  let ttInfo = { hasCookies: false };
  let xInfo = { hasCookies: false };

  if (igExists) {
    try {
      const stat = fs.statSync(IG_COOKIES_PATH);
      const content = fs.readFileSync(IG_COOKIES_PATH, 'utf8');
      const hasInstagram = content.includes('instagram.com');
      igInfo = {
        hasCookies: true,
        hasInstagram,
        savedAt: stat.mtimeMs,
        sizeBytes: stat.size,
      };
    } catch {}
  }

  if (ttExists) {
    try {
      const stat = fs.statSync(TT_COOKIES_PATH);
      const content = fs.readFileSync(TT_COOKIES_PATH, 'utf8');
      const hasTikTok = content.includes('tiktok.com');
      ttInfo = {
        hasCookies: true,
        hasTikTok,
        savedAt: stat.mtimeMs,
        sizeBytes: stat.size,
      };
    } catch {}
  }

  if (xExists) {
    try {
      const stat = fs.statSync(X_COOKIES_PATH);
      const content = fs.readFileSync(X_COOKIES_PATH, 'utf8');
      const hasX = content.includes('x.com') || content.includes('twitter.com');
      xInfo = {
        hasCookies: true,
        hasX,
        savedAt: stat.mtimeMs,
        sizeBytes: stat.size,
      };
    } catch {}
  }

  res.json({
    success: true,
    data: {
      instagram: igInfo,
      tiktok: ttInfo,
      x: xInfo,
      // Backward compatibility fields for frontend:
      hasCookies: igExists,
      hasInstagram: igExists && igInfo.hasInstagram,
      savedAt: igExists ? igInfo.savedAt : null,
      sizeBytes: igExists ? igInfo.sizeBytes : null,
    },
  });
});

// POST /api/instagram-frames/save-cookies
// Body: { cookies: "<netscape cookies.txt content>", platform?: "instagram" | "tiktok" | "x" }
router.post('/save-cookies', (req, res, next) => {
  try {
    const { cookies, platform } = req.body;
    if (!cookies || typeof cookies !== 'string' || cookies.trim().length < 20) {
      throw new AppError('Invalid cookies content', 400, 'VALIDATION_ERROR');
    }
    let trimmed = cookies.trim();
    // Accept browser-extension JSON cookie exports too (Cookie-Editor etc.) — convert them.
    if (trimmed.startsWith('[')) {
      const converted = jsonCookiesToNetscape(trimmed);
      if (!converted) {
        throw new AppError('Could not parse the JSON cookies. Paste a valid cookie export.', 400, 'VALIDATION_ERROR');
      }
      trimmed = converted;
    } else if (!trimmed.startsWith('# Netscape HTTP Cookie File') && !trimmed.includes('\tTRUE\t') && !trimmed.includes('\tFALSE\t')) {
      throw new AppError('This doesn\'t look like a Netscape cookies.txt or JSON cookie export. Use the "Get cookies.txt LOCALLY" or "Cookie-Editor" browser extension.', 400, 'VALIDATION_ERROR');
    }

    let targetPath = IG_COOKIES_PATH;
    let selectedPlatform = 'instagram';

    if (platform === 'tiktok' || (platform !== 'instagram' && platform !== 'x' && trimmed.includes('tiktok.com'))) {
      targetPath = TT_COOKIES_PATH;
      selectedPlatform = 'tiktok';
    } else if (platform === 'x' || (platform !== 'instagram' && platform !== 'tiktok' && (trimmed.includes('x.com') || trimmed.includes('twitter.com')))) {
      targetPath = X_COOKIES_PATH;
      selectedPlatform = 'x';
    }

    fs.writeFileSync(targetPath, trimmed, 'utf8');
    log.info('cookies_saved', { platform: selectedPlatform, size: trimmed.length });
    res.json({ success: true, data: { saved: true, platform: selectedPlatform } });
  } catch (err) {
    next(err);
  }
});

// DELETE /api/instagram-frames/cookies
// Query/Body: { platform?: "instagram" | "tiktok" | "x" }
router.delete('/cookies', (req, res) => {
  try {
    const platform = req.query.platform || req.body.platform;
    if (platform === 'tiktok') {
      if (fs.existsSync(TT_COOKIES_PATH)) fs.unlinkSync(TT_COOKIES_PATH);
    } else if (platform === 'instagram') {
      if (fs.existsSync(IG_COOKIES_PATH)) fs.unlinkSync(IG_COOKIES_PATH);
    } else if (platform === 'x') {
      if (fs.existsSync(X_COOKIES_PATH)) fs.unlinkSync(X_COOKIES_PATH);
    } else {
      if (fs.existsSync(IG_COOKIES_PATH)) fs.unlinkSync(IG_COOKIES_PATH);
      if (fs.existsSync(TT_COOKIES_PATH)) fs.unlinkSync(TT_COOKIES_PATH);
      if (fs.existsSync(X_COOKIES_PATH)) fs.unlinkSync(X_COOKIES_PATH);
    }
  } catch {}
  res.json({ success: true });
});

// GET /api/instagram-frames/proxy — current scraper proxy (masked)
router.get('/proxy', (req, res) => {
  const proxy = resolveScraperProxy();
  res.json({ success: true, data: { hasProxy: !!proxy, proxy: proxy ? proxy.replace(/:\/\/[^@]+@/, '://***@') : '' } });
});

// POST /api/instagram-frames/proxy — save/clear scraper proxy.  Body: { proxy }
router.post('/proxy', (req, res, next) => {
  try {
    const { proxy } = req.body;
    if (typeof proxy !== 'string') throw new AppError('proxy must be a string', 400, 'VALIDATION_ERROR');
    const v = proxy.trim();
    if (v === '') {
      try { if (fs.existsSync(SCRAPER_PROXY_PATH)) fs.unlinkSync(SCRAPER_PROXY_PATH); } catch {}
      return res.json({ success: true, data: { hasProxy: false } });
    }
    if (!/^(https?|socks5h?):\/\//i.test(v)) {
      throw new AppError('Proxy must start with http://, https://, or socks5://', 400, 'VALIDATION_ERROR');
    }
    fs.writeFileSync(SCRAPER_PROXY_PATH, v, 'utf8');
    log.info('scraper_proxy_saved', {});
    res.json({ success: true, data: { hasProxy: true } });
  } catch (err) {
    next(err);
  }
});

// ── Fisher-Yates shuffle (in-place) ─────────────────────────────────────────
function shuffleArray(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

const IG_PROFILE_RE = /https?:\/\/(www\.)?instagram\.com\/([A-Za-z0-9_.]+)(\/reels|\/videos|\/posts)?\/?/i;

// POST /api/instagram-frames/grab-profile
// Body: { profileUrl, count, frameMode }
// - profileUrl: https://www.instagram.com/username/ or /username/reels/
// - count: 10 | 20 | 50 (default 10)
// - frameMode: 'smart' | 'brain' | 'thumb' (default 'thumb')
// Returns a stream of SSE events: { type: 'frame', frame: {base64,mimeType,name,sourceUrl} }
//                                 { type: 'progress', done, total }
//                                 { type: 'done', totalSaved }
//                                 { type: 'error', message }
router.post('/grab-profile', async (req, res, next) => {
  const downloadDir = path.join(getTempDir(), `profile-grab-${crypto.randomUUID()}`);
  try {
    const { profileUrl, count = 10, frameMode = 'thumb', multiFrameCount, intervalMs, useApify, excludeShortcodes } = req.body;
    // Shortcodes the client has already grabbed from THIS profile before — skip them so a
    // repeat grab surfaces genuinely new reels instead of reshuffling the same small pool.
    const excludeSet = new Set(Array.isArray(excludeShortcodes) ? excludeShortcodes.filter((s) => typeof s === 'string') : []);
    if (!profileUrl || typeof profileUrl !== 'string') {
      throw new AppError('"profileUrl" is required', 400, 'VALIDATION_ERROR');
    }
    if (!IG_PROFILE_RE.test(profileUrl)) {
      throw new AppError('URL must be an Instagram profile or reels page (instagram.com/username/)', 400, 'VALIDATION_ERROR');
    }

    const cookiesExist = fs.existsSync(IG_COOKIES_PATH);
    // If useApify is explicitly requested and no cookies, skip cookie check
    if (!cookiesExist && !useApify) {
      throw new AppError('Instagram cookies required. Set them up in the cookies section first, or enable the Apify fallback toggle.', 401, 'NO_COOKIES');
    }

    const wantCount = Math.max(1, Math.min(100, Number(count) || 10));
    const scraperProxy = resolveScraperProxy();

    const profileMatch = profileUrl.match(IG_PROFILE_RE);
    const username = profileMatch?.[2] || '';
    // Try /reels/ sub-path first so gallery-dl only fetches video posts
    const targetUrl = `https://www.instagram.com/${username}/reels/`;

    log.info('ig_profile_grab_start', { username, wantCount, frameMode, multiFrameCount, intervalMs });

    fs.mkdirSync(downloadDir, { recursive: true });

    // ── Start streaming immediately so the client isn't staring at nothing ────
    res.setHeader('Content-Type', 'application/x-ndjson');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.setHeader('Cache-Control', 'no-cache');
    res.flushHeaders();

    const send = (obj) => { if (!res.writableEnded) res.write(JSON.stringify(obj) + '\n'); };

    // ── Step 1: download reels with gallery-dl ────────────────────────────────
    // Send live download count to the client while gallery-dl works.
    const galleryDl = findGalleryDl();
    const maxFetch = wantCount + 2;

    const dlArgs = [
      '--cookies', IG_COOKIES_PATH,
      '--directory', downloadDir,
      '--filename', '{post_shortcode}_{num}.{extension}',
      '--range', `1-${maxFetch}`,
      '--quiet',
    ];
    if (scraperProxy) dlArgs.push('--proxy', scraperProxy);
    dlArgs.push(targetUrl);

    send({ type: 'phase', phase: 'downloading', message: `Downloading reels from @${username}…` });

    // Poll the download dir every 2s to report how many files have landed
    const VIDEO_EXTS = new Set(['.mp4', '.mov', '.webm', '.m4v', '.mkv']);
    let dlFileCount = 0;
    const dlPollInterval = setInterval(() => {
      try {
        const count = fs.readdirSync(downloadDir).filter(f => VIDEO_EXTS.has(path.extname(f).toLowerCase())).length;
        if (count !== dlFileCount) {
          dlFileCount = count;
          send({ type: 'download_progress', downloaded: dlFileCount });
        }
      } catch {}
    }, 2000);

    try {
      await execFileAsync(galleryDl, dlArgs, { timeout: 240_000, maxBuffer: 5 * 1024 * 1024 });
    } catch (dlErr) {
      const msg = String(dlErr.stderr || dlErr.message || '');
      // "NotFoundError: Requested user could not be found" is gallery-dl's phrasing when its
      // username→user_id lookup fails — this fires for ANY account (even huge public ones)
      // once the session cookies stop being recognized as logged-in, not just for genuinely
      // private/nonexistent accounts. Route it through the same cookie-expiry message instead
      // of silently falling through to the vague "may be private" catch-all below, which
      // misleads the user about the real cause.
      if (/login|sign.?in|private|cookie|unauthorized|notfounderror|could not be found/i.test(msg)) {
        clearInterval(dlPollInterval);
        if (useApify) {
          log.warn('ig_profile_grab_dl_session_dead_falling_back_to_apify', { username, msg: msg.slice(0, 200) });
        } else {
          throw new AppError(
            `Instagram didn't recognize your session for @${username} (this happens for ANY account, not just this one, once cookies go stale — it is not necessarily about this profile being private). Re-export fresh cookies, or enable "Use Apify if cookies fail" below (it doesn't need cookies at all).`,
            401,
            'COOKIES_EXPIRED'
          );
        }
      } else {
        log.warn('ig_profile_grab_dl_partial', { username, msg: msg.slice(0, 200) });
      }
    }
    clearInterval(dlPollInterval);

    // ── Step 2: collect video files ────────────────────────────────────────────
    // Also build reel link list from filenames (shortcodes) for the links panel
    function findVideos(dir) {
      const files = [];
      try {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          const full = path.join(dir, entry.name);
          if (entry.isDirectory()) files.push(...findVideos(full));
          else if (VIDEO_EXTS.has(path.extname(entry.name).toLowerCase())) files.push(full);
        }
      } catch {}
      return files;
    }

    const allVideoFiles = findVideos(downloadDir);

    // If gallery-dl found nothing and useApify is enabled, try Apify profile scraper
    if (allVideoFiles.length === 0 && useApify) {
      clearInterval(dlPollInterval);
      const apiKeyManager = require('../services/apiKeyManager');
      let apifyToken = '';
      try { apifyToken = apiKeyManager.getApifyKey(); } catch {}
      if (!apifyToken) {
        throw new AppError('No Apify API key. Add it in API Keys settings.', 422, 'NO_APIFY_KEY');
      }
      send({ type: 'phase', phase: 'apify', message: `Gallery-dl found nothing. Trying Apify for @${username}…` });
      const axios = require('axios');
      const apifyUrl = `https://api.apify.com/v2/acts/apify~instagram-scraper/run-sync-get-dataset-items?token=${encodeURIComponent(apifyToken)}`;
      // Use the /reels/ tab, not the profile root — tested both against this account: /reels/
      // yielded far more actual video posts (11 of 20 requested) than the plain profile root
      // (2 of 20), so despite being a client-rendered view, Apify's actor clearly biases
      // toward real reel content there. Push the buffer high since Apify's own yield per run
      // is the real bottleneck, not our filtering.
      const apifyBody = {
        directUrls: [`https://www.instagram.com/${username}/reels/`],
        resultsType: 'posts',
        resultsLimit: Math.min(200, wantCount * 10),
      };
      let apifyItems = [];
      try {
        const resp = await axios.post(apifyUrl, apifyBody, { timeout: 180_000 });
        apifyItems = Array.isArray(resp.data) ? resp.data : [];
      } catch (apErr) {
        throw new AppError(`Apify scrape failed: ${apErr.message}`, 502, 'APIFY_ERROR');
      }
      // Reels only — drop photo/carousel posts entirely (no videoUrl = not a reel). Then drop
      // anything the client already grabbed from this profile before, so a repeat grab
      // surfaces genuinely new reels instead of reshuffling the same small pool. Shuffle what's
      // left so a fresh grab (no exclusions yet) still varies pick order run to run.
      const allVideoItems = apifyItems.filter((item) => !!(item.videoUrl || item.video_url));
      const videoItems = excludeSet.size ? allVideoItems.filter((item) => !excludeSet.has(item.shortCode)) : allVideoItems;
      const alreadyGrabbedSkippedApify = allVideoItems.length - videoItems.length;
      shuffleArray(videoItems);
      const selectedItems = videoItems.slice(0, wantCount);
      if (apifyItems.length > 0 && videoItems.length < wantCount) {
        log.info('ig_profile_grab_apify_fewer_reels_than_requested', { username, requested: wantCount, rawFetched: apifyItems.length, videoOnly: allVideoItems.length, freshAfterExclude: videoItems.length, alreadyGrabbedSkippedApify });
      }

      const reelLinks = [];
      let saved = 0;
      send({ type: 'progress', done: 0, total: selectedItems.length });
      for (let i = 0; i < selectedItems.length; i++) {
        const item = selectedItems[i];
        const videoUrl = item.videoUrl || item.video_url;
        const postUrl = item.url || (item.shortCode ? `https://www.instagram.com/reel/${item.shortCode}/` : null);
        if (postUrl) reelLinks.push(postUrl);
        send({ type: 'reel_link', url: postUrl || '' });
        try {
          const sessionDir = path.join(getTempDir(), crypto.randomUUID());
          fs.mkdirSync(sessionDir, { recursive: true });
          const videoPath = path.join(sessionDir, `apify_reel_${i}.mp4`);
          const vidResp = await axios.get(videoUrl, { responseType: 'arraybuffer', timeout: 60_000 });
          fs.writeFileSync(videoPath, Buffer.from(vidResp.data));
          const frameDir = path.join(sessionDir, 'frames');
          fs.mkdirSync(frameDir, { recursive: true });
          const shortCode = item.shortCode || `apify-${i}`;
          const resolvedSourceUrl = postUrl || `https://www.instagram.com/reel/${shortCode}/`;

          // Multi-frame mode (same as the gallery-dl path): pull N frames at the requested
          // interval, not just a single thumbnail per reel.
          const mfCount = multiFrameCount && multiFrameCount > 1 ? Math.max(1, Math.min(60, Number(multiFrameCount) || 10)) : 1;
          let multiFrameFiles = [];
          if (mfCount > 1) {
            const mfInterval = Math.max(50, Math.min(2000, Number(intervalMs) || 200));
            const fpsValue = (1000 / mfInterval).toFixed(4);
            try {
              await execFileAsync(ffmpegPath, ['-i', videoPath, '-vf', `fps=${fpsValue}`, '-frames:v', String(mfCount), '-q:v', '3', path.join(frameDir, 'frame_%03d.jpg')], { timeout: 30_000 });
              multiFrameFiles = fs.readdirSync(frameDir).filter(f => f.endsWith('.jpg')).sort();
            } catch (ffErr) {
              log.warn('apify_profile_multi_frame_failed', { error: ffErr.message });
            }
            if (multiFrameFiles.length > 0) {
              for (let fi = 0; fi < multiFrameFiles.length; fi++) {
                const buf = fs.readFileSync(path.join(frameDir, multiFrameFiles[fi]));
                saved++;
                send({ type: 'frame', frame: { base64: buf.toString('base64'), mimeType: 'image/jpeg', name: `${username}-${String(saved).padStart(3, '0')}.jpg`, sourceUrl: resolvedSourceUrl, timestampMs: Math.round(fi * mfInterval) } });
              }
            }
          }

          // Single-frame fallback: multi-frame mode is off, or ffmpeg's fps sampling failed.
          if (mfCount <= 1 || multiFrameFiles.length === 0) {
            const frameOut = path.join(frameDir, 'frame_001.jpg');
            try {
              await execFileAsync(ffmpegPath, ['-i', videoPath, '-vf', 'thumbnail=n=300', '-frames:v', '1', '-q:v', '2', frameOut], { timeout: 45_000 });
            } catch {
              await execFileAsync(ffmpegPath, ['-ss', '0.2', '-i', videoPath, '-frames:v', '1', '-q:v', '2', frameOut], { timeout: 30_000 });
            }
            if (fs.existsSync(frameOut)) {
              const buf = fs.readFileSync(frameOut);
              saved++;
              send({ type: 'frame', frame: { base64: buf.toString('base64'), mimeType: 'image/jpeg', name: `${username}-${String(saved).padStart(3,'0')}.jpg`, sourceUrl: resolvedSourceUrl } });
            }
          }
          cleanupDir(sessionDir);
        } catch (frameErr) {
          log.warn('apify_profile_frame_failed', { i, error: frameErr.message });
          send({ type: 'video_error', url: postUrl || `apify-${i}`, message: frameErr.message });
        }
        send({ type: 'progress', done: i + 1, total: selectedItems.length });
      }
      send({ type: 'done', totalSaved: saved, totalAttempted: selectedItems.length, reelLinks, newShortcodes: selectedItems.map((it) => it.shortCode).filter(Boolean), alreadyGrabbedSkipped: alreadyGrabbedSkippedApify });
      res.end();
      return;
    }

    if (allVideoFiles.length === 0) {
      throw new AppError(
        'No reels downloaded. The profile may be private, have no reels, or cookies may be expired. Check cookies in Settings.',
        422,
        'NO_REELS_FOUND',
      );
    }

    // ── Step 3: exclude already-grabbed reels, shuffle, pick N ────────────────
    const fileShortcode = (f) => path.basename(f).replace(/\.[^.]+$/, '').replace(/_\d+$/, '');
    const freshVideoFiles = excludeSet.size ? allVideoFiles.filter((f) => !excludeSet.has(fileShortcode(f))) : allVideoFiles;
    const alreadyGrabbedSkipped = allVideoFiles.length - freshVideoFiles.length;
    shuffleArray(freshVideoFiles);
    const selectedFiles = freshVideoFiles.slice(0, wantCount);

    log.info('ig_profile_grab_selected', { username, total: allVideoFiles.length, fresh: freshVideoFiles.length, alreadyGrabbedSkipped, selected: selectedFiles.length });

    // ── Step 4: extract frames ────────────────────────────────────────────────
    send({ type: 'phase', phase: 'extracting', message: `Extracting frames from ${selectedFiles.length} reels…` });
    send({ type: 'progress', done: 0, total: selectedFiles.length });

    let saved = 0;
    let idx = 0;
    const CONCURRENCY = 2;

    async function processOneFile(videoFile) {
      const sessionDir = path.join(getTempDir(), crypto.randomUUID());
      try {
        fs.mkdirSync(sessionDir, { recursive: true });
        const framesDir = path.join(sessionDir, 'frames');
        fs.mkdirSync(framesDir, { recursive: true });

        // Multi-frame mode: extract N frames at given interval (like regular extract)
        if (multiFrameCount && multiFrameCount > 1) {
          const mfCount = Math.max(1, Math.min(60, Number(multiFrameCount) || 10));
          const mfInterval = Math.max(50, Math.min(2000, Number(intervalMs) || 200));
          const fpsValue = (1000 / mfInterval).toFixed(4);
          const framePattern = path.join(framesDir, 'frame_%03d.jpg');
          log.info('grab_profile_multi_frame', { multiFrameCount: mfCount, intervalMs: mfInterval, fps: fpsValue, videoFile: path.basename(videoFile) });
          try {
            await execFileAsync(ffmpegPath, [
              '-i', videoFile,
              '-vf', `fps=${fpsValue}`,
              '-frames:v', String(mfCount),
              '-q:v', '3',
              framePattern,
            ], { timeout: 30_000 });
          } catch (ffErr) {
            log.warn('grab_profile_multi_frame_ffmpeg_failed', { error: ffErr.message, file: path.basename(videoFile) });
            // Fall through to single-frame extraction below
          }
          const frameFiles = fs.readdirSync(framesDir).filter(f => f.endsWith('.jpg')).sort();
          if (frameFiles.length > 0) {
            const sourceLabel = path.basename(videoFile).replace(/\.[^.]+$/, '');
            for (let fi = 0; fi < frameFiles.length; fi++) {
              const buf = fs.readFileSync(path.join(framesDir, frameFiles[fi]));
              saved++;
              send({ type: 'frame', frame: { base64: buf.toString('base64'), mimeType: 'image/jpeg', name: `${username}-${String(saved).padStart(3, '0')}.jpg`, sourceUrl: sourceLabel, timestampMs: Math.round(fi * mfInterval) } });
            }
            return;
          }
          log.warn('grab_profile_multi_frame_no_files', { file: path.basename(videoFile) });
          // Fall through to single-frame extraction
        }

        // AI brain: Gemini picks the best face frame
        if (frameMode === 'brain' || frameMode === 'smart') {
          try {
            const smartFrames = await smartPickFrames(videoFile, sessionDir);
            if (smartFrames.length > 0) {
              saved++;
              const sf = smartFrames[0];
              send({ type: 'frame', frame: { base64: sf.base64, mimeType: sf.mimeType || 'image/jpeg', name: `${username}-${String(saved).padStart(3, '0')}.jpg`, sourceUrl: videoFile } });
              return;
            }
          } catch { /* fall through to ffmpeg */ }
        }

        const frameOutPath = path.join(framesDir, 'frame_001.jpg');
        if (frameMode === 'quick') {
          // Quick: grab frame at ~200ms
          await execFileAsync(ffmpegPath, [
            '-ss', '0.2', '-i', videoFile,
            '-frames:v', '1', '-q:v', '2', frameOutPath,
          ], { timeout: 30_000 });
        } else {
          // Thumbnail: ffmpeg picks most representative frame
          await execFileAsync(ffmpegPath, [
            '-i', videoFile,
            '-vf', 'thumbnail=n=300',
            '-frames:v', '1', '-q:v', '2', frameOutPath,
          ], { timeout: 45_000 });
        }

        if (!fs.existsSync(frameOutPath)) throw new Error('No frame extracted');
        const buf = fs.readFileSync(frameOutPath);
        saved++;
        send({ type: 'frame', frame: { base64: buf.toString('base64'), mimeType: 'image/jpeg', name: `${username}-${String(saved).padStart(3, '0')}.jpg`, sourceUrl: path.basename(videoFile) } });
      } catch (err) {
        log.warn('ig_profile_grab_video_failed', { file: path.basename(videoFile), error: err.message });
        send({ type: 'video_error', url: path.basename(videoFile), message: err.message });
      } finally {
        cleanupDir(sessionDir);
        idx++;
        send({ type: 'progress', done: idx, total: selectedFiles.length });
      }
    }

    const queue = [...selectedFiles];
    const workers = Array.from({ length: CONCURRENCY }, async () => {
      while (queue.length > 0) {
        const f = queue.shift();
        if (f) await processOneFile(f);
      }
    });
    await Promise.all(workers);

    // Build final reel links list from the video filenames (shortcodes)
    const reelLinks = selectedFiles.map(f => {
      const base = path.basename(f).replace(/\.[^.]+$/, '');
      // gallery-dl names files as {shortcode}_{num}.ext, strip trailing _num
      const shortCode = base.replace(/_\d+$/, '');
      return `https://www.instagram.com/reel/${shortCode}/`;
    });

    log.info('ig_profile_grab_done', { username, saved, total: selectedFiles.length, alreadyGrabbedSkipped });
    send({ type: 'done', totalSaved: saved, totalAttempted: selectedFiles.length, reelLinks, newShortcodes: selectedFiles.map(fileShortcode), alreadyGrabbedSkipped });
    res.end();
  } catch (err) {
    if (!res.headersSent) return next(err);
    if (!res.writableEnded) {
      res.write(JSON.stringify({ type: 'error', message: err.message || 'Failed' }) + '\n');
      res.end();
    }
  } finally {
    // Clean up all downloaded source videos after we're done streaming
    try { cleanupDir(downloadDir); } catch {}
  }
});



// POST /api/instagram-frames/resolve-media-batch

// Body: { urls: [...] } — runs ONE Apify job for all Instagram links and returns each
// post's public CDN media URL. No cookies, no IP block (Apify scrapes on its side).
router.post('/resolve-media-batch', async (req, res, next) => {
  try {
    const { urls } = req.body;
    if (!Array.isArray(urls) || urls.length === 0) throw new AppError('"urls" array is required', 400, 'VALIDATION_ERROR');
    const apiKeyManager = require('../services/apiKeyManager');
    let token = '';
    try { token = apiKeyManager.getApifyKey(); } catch {}
    if (!token) throw new AppError('No Apify API key set. Add it in API Keys first.', 400, 'NO_APIFY_KEY');

    const clean = urls.filter((u) => typeof u === 'string' && u.startsWith('http')).slice(0, 500);
    const axios = require('axios');
    const resp = await axios.post(
      `https://api.apify.com/v2/acts/apify~instagram-scraper/run-sync-get-dataset-items?token=${encodeURIComponent(token)}`,
      { directUrls: clean, resultsLimit: clean.length, resultsType: 'posts', addParentData: false },
      { timeout: 300_000, headers: { 'Content-Type': 'application/json' } }
    );
    const items = Array.isArray(resp.data) ? resp.data : [];
    // Do NOT guess 'Image' when the type is missing — a partial Apify response for a reel can
    // arrive with only a displayUrl (its ▶ cover), and defaulting it to 'Image' would make the
    // client save that cover. Leave unknown types blank so the client fails safe + retries.
    const typeOf = (o) => o.type || (o.videoUrl ? 'Video' : '');
    const out = items.map((it) => ({
      url: it.url || it.inputUrl || '',
      type: typeOf(it),
      productType: it.productType || null,
      videoUrl: it.videoUrl || null,
      displayUrl: it.displayUrl || it.image || (Array.isArray(it.images) ? it.images[0] : null) || null,
      // Carousels (Sidecar) only carry a cover at the top level — expose each slide so the
      // client can pick a real one (a video slide → frame it; an image slide → use it) and
      // never save the carousel's ▶ cover.
      childPosts: Array.isArray(it.childPosts) ? it.childPosts.map((c) => ({
        type: typeOf(c),
        videoUrl: c.videoUrl || null,
        displayUrl: c.displayUrl || null,
      })) : [],
      error: it.error || it.errorDescription || null,
    }));
    log.info('apify_resolve_batch', { requested: clean.length, returned: out.length, withMedia: out.filter((o) => o.videoUrl || o.displayUrl).length });
    res.json({ success: true, data: { items: out } });
  } catch (err) {
    if (err.response) {
      log.warn('apify_resolve_batch_http', { status: err.response.status });
      return next(new AppError(`Apify error ${err.response.status}. Check your Apify key/credits.`, 502, 'APIFY_ERROR'));
    }
    next(err);
  }
});

// POST /api/instagram-frames/extract-from-media
// Body: { mediaUrl, mediaType, smartPick } — download a PUBLIC CDN url (no cookies) and
// smart-pick a frame (for video) or return it (for image).
router.post('/extract-from-media', async (req, res, next) => {
  const sessionDir = path.join(getTempDir(), crypto.randomUUID());
  try {
    const { mediaUrl, mediaType = 'video', smartPick = true } = req.body;
    if (!mediaUrl || typeof mediaUrl !== 'string' || !mediaUrl.startsWith('http')) {
      throw new AppError('"mediaUrl" is required', 400, 'VALIDATION_ERROR');
    }
    fs.mkdirSync(sessionDir, { recursive: true });
    const axios = require('axios');
    const isVideo = /video/i.test(String(mediaType));

    if (!isVideo) {
      const resp = await axios.get(mediaUrl, { responseType: 'arraybuffer', timeout: 60_000 });
      const ct = String(resp.headers['content-type'] || 'image/jpeg');
      const mime = ct.includes('png') ? 'image/png' : ct.includes('webp') ? 'image/webp' : 'image/jpeg';
      return res.json({ success: true, data: { frames: [{ index: 0, timestampMs: 0, base64: Buffer.from(resp.data).toString('base64'), mimeType: mime }] } });
    }

    const videoPath = path.join(sessionDir, 'video.mp4');
    const resp = await axios.get(mediaUrl, { responseType: 'arraybuffer', timeout: 120_000 });
    fs.writeFileSync(videoPath, Buffer.from(resp.data));
    const framesDir = path.join(sessionDir, 'frames');
    fs.mkdirSync(framesDir, { recursive: true });
    const vf = smartPick ? 'thumbnail=n=500' : 'thumbnail=n=100';
    await execFileAsync(ffmpegPath, ['-i', videoPath, '-vf', vf, '-frames:v', '1', '-q:v', '2', path.join(framesDir, 'frame_001.jpg')], { timeout: 45_000 });
    const frameFiles = fs.readdirSync(framesDir).filter((f) => f.endsWith('.jpg'));
    if (!frameFiles.length) throw new AppError('No frame could be extracted', 422, 'NO_FRAMES');
    const buf = fs.readFileSync(path.join(framesDir, frameFiles[0]));
    res.json({ success: true, data: { frames: [{ index: 0, timestampMs: 0, base64: buf.toString('base64'), mimeType: 'image/jpeg' }] } });
  } catch (err) {
    if (err.response) return next(new AppError(`Could not download media (${err.response.status}).`, 502, 'MEDIA_DOWNLOAD_FAILED'));
    next(err);
  } finally {
    cleanupDir(sessionDir);
  }
});

// POST /api/instagram-frames/extract-from-upload?smartPick=1&type=video/mp4
// Body: raw video bytes (Content-Type: application/octet-stream). Smart-picks a representative
// frame with ffmpeg. Lets you pull a frame from a video you already have on disk (e.g. an
// age-gated / banned post the scraper can't fetch) by dropping the file into the Frame Library.
router.post('/extract-from-upload', express.raw({ type: 'application/octet-stream', limit: '300mb' }), async (req, res, next) => {
  const sessionDir = path.join(getTempDir(), crypto.randomUUID());
  try {
    const buf = req.body;
    if (!Buffer.isBuffer(buf) || buf.length === 0) throw new AppError('No video data received', 400, 'VALIDATION_ERROR');
    const smartPick = String(req.query.smartPick ?? '1') !== '0';
    const t = String(req.query.type || '');
    const ext = /webm/i.test(t) ? '.webm' : /(quicktime|mov)/i.test(t) ? '.mov' : /(m4v|mp4)/i.test(t) ? '.mp4' : '.mp4';
    fs.mkdirSync(sessionDir, { recursive: true });
    const videoPath = path.join(sessionDir, `upload${ext}`);
    fs.writeFileSync(videoPath, buf);
    const framesDir = path.join(sessionDir, 'frames');
    fs.mkdirSync(framesDir, { recursive: true });
    const vf = smartPick ? 'thumbnail=n=500' : 'thumbnail=n=100';
    try {
      await execFileAsync(ffmpegPath, ['-i', videoPath, '-vf', vf, '-frames:v', '1', '-q:v', '2', path.join(framesDir, 'frame_001.jpg')], { timeout: 60_000 });
    } catch (ffErr) {
      log.warn('upload_frame_ffmpeg_failed', { error: ffErr.message });
      throw new AppError('Could not read that video — is it a supported format (mp4/mov/webm)?', 422, 'FFMPEG_FAILED');
    }
    const frameFiles = fs.readdirSync(framesDir).filter((f) => f.endsWith('.jpg'));
    if (!frameFiles.length) throw new AppError('No frame could be extracted from the video', 422, 'NO_FRAMES');
    const out = fs.readFileSync(path.join(framesDir, frameFiles[0]));
    res.json({ success: true, data: { frames: [{ index: 0, timestampMs: 0, base64: out.toString('base64'), mimeType: 'image/jpeg' }] } });
  } catch (err) {
    next(err);
  } finally {
    cleanupDir(sessionDir);
  }
});

// Shared "smart" frame picker — TWO-STAGE approach:
// Stage 1: Extract many frames (4fps, up to 120), pre-filter black/tiny, downselect to 20.
// Stage 2: Send 20 candidates to Gemini → ranked top-3 best + face + outfit frames.
// Returns [{ label, base64, mimeType }]. User gets multiple good options, not just one guess.
async function smartPickFrames(videoPath, sessionDir) {
  const framesDir = path.join(sessionDir, 'frames');
  fs.mkdirSync(framesDir, { recursive: true });

  // ── STAGE 1: Extract & pre-filter ──────────────────────────────────────────
  // 4fps × 30s = ~120 frames. Quality 1 = max JPEG quality for sharp candidates.
  try {
    await execFileAsync(ffmpegPath, [
      '-i', videoPath,
      '-vf', 'fps=4',
      '-frames:v', '120',
      '-q:v', '1',
      path.join(framesDir, 'cand_%04d.jpg'),
    ], { timeout: 120_000 });
  } catch (ffErr) {
    log.warn('smart_frame_ffmpeg_failed', { error: ffErr.message });
    throw new AppError('Could not read that video — is it a supported format (mp4/mov/webm)?', 422, 'FFMPEG_FAILED');
  }

  let allFrames = fs.readdirSync(framesDir).filter((f) => f.endsWith('.jpg')).sort();
  if (!allFrames.length) throw new AppError('No frames could be sampled from the video', 422, 'NO_FRAMES');

  // Pre-filter: kill black/transition frames (they're tiny because JPEG compresses solid
  // colors to almost nothing). Any frame under 8KB is likely black or a solid-color transition.
  const MIN_FILE_SIZE = 8_000;
  allFrames = allFrames.filter((f) => {
    try { return fs.statSync(path.join(framesDir, f)).size >= MIN_FILE_SIZE; } catch { return true; }
  });
  if (!allFrames.length) {
    // All filtered out — re-read without filter
    allFrames = fs.readdirSync(framesDir).filter((f) => f.endsWith('.jpg')).sort();
  }

  // Downselect to 20 evenly spaced candidates for Gemini
  const MAX_CAND = 20;
  const step = Math.max(1, Math.floor(allFrames.length / MAX_CAND));
  const picked = [];
  for (let i = 0; i < allFrames.length && picked.length < MAX_CAND; i += step) picked.push(allFrames[i]);
  const images = picked.map((f) => ({ base64Data: fs.readFileSync(path.join(framesDir, f)).toString('base64'), mimeType: 'image/jpeg' }));

  log.info('smart_pick_stage1', { totalExtracted: allFrames.length, afterFilter: allFrames.length, candidates: images.length });

  // ── STAGE 2: Gemini vision ranking ─────────────────────────────────────────
  const prompt = `You are given ${images.length} still frames (numbered 1 to ${images.length}, in time order) sampled from a short social media video of ONE person.

Your job: RANK the frames and return the BEST options. Return ONLY minified JSON, no markdown fences, exactly this shape:
{"top3": [<number>, <number>, <number>], "faceFrame": <number>, "outfitFrames": [<number>, ...]}

RANKING RULES for top3 — rank the 3 BEST frames in order (index 0 = absolute best). Each frame in top3 MUST satisfy ALL of these:
  1. FACE CLEARLY VISIBLE — her face is turned toward the camera, eyes WIDE OPEN (not mid-blink, not squinting, not closed), mouth natural (not wide open mid-speech/yawn)
  2. FACE NOT COVERED — no hands, hair, phone, hat, clothing, props, or text covering any part of the face
  3. SHARP FOCUS — no motion blur on the face or body, crisp details, not blurry
  4. BODY VISIBLE — as much body visible as possible (head-to-toe preferred, at minimum head-to-waist). NOT just a head/shoulders crop, NOT shot from behind
  5. GOOD POSE — natural, flattering, not awkward mid-movement or mid-transition
  6. WELL LIT — face and body clearly illuminated, not in heavy shadow or overexposed
  7. FRONT-FACING — she is facing TOWARD the camera. Profile views, back views, and side angles are WORSE than front-facing or 3/4 angles

The 3 frames in top3 should be DIFFERENT moments (not adjacent/similar). Spread them across the video.

faceFrame = The single frame with the ABSOLUTE CLEAREST view of her face:
  - Eyes MUST be open and looking forward/at camera
  - Face fully unobstructed — nothing covering any facial feature
  - Sharpest focus on face (no motion blur)
  - Closest to front-facing as possible
  - Can be the same as top3[0] if that's also the best face

outfitFrames = One frame per DISTINCT complete outfit she is WEARING (not holding):
  - Show the full outfit clearly — prefer wider/full-body shots
  - Face also visible if possible
  - One entry per distinct outfit; if only one outfit, one number

HARD DISQUALIFICATION — a frame CANNOT be in top3 or faceFrame if ANY of these are true:
  ✗ Eyes closed, mid-blink, or squinting
  ✗ Face turned AWAY from camera (back of head, looking away, profile)
  ✗ Face covered/blocked by hands, hair, phone, props, text overlay, or graphics
  ✗ Heavy motion blur (person or camera shaking)
  ✗ Person mostly out of frame, cut off at neck, or only showing back/behind
  ✗ Black/dark frame, transition frame, or title card
  ✗ Face in heavy shadow or silhouette

If fewer than 3 frames pass all criteria, return only the ones that do.
Use 1-based frame numbers only. No other text.`;

  const apiKeyManager = require('../services/apiKeyManager');
  const geminiBackend = require('../services/geminiBackend');
  const apiKey = apiKeyManager.getActiveKey();
  const text = await geminiBackend.analyzeImagesWithPrompt(apiKey, images, prompt);

  let parsed = null;
  try {
    parsed = JSON.parse(String(text).trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, ''));
  } catch {
    const m = String(text).match(/\{[\s\S]*\}/);
    if (m) { try { parsed = JSON.parse(m[0]); } catch { /* ignore */ } }
  }

  const clamp = (n) => (Number.isInteger(n) && n >= 1 && n <= images.length ? n - 1 : -1);
  const out = [];
  const seen = new Set();

  // Top 3 ranked frames (best options for the user)
  const top3 = Array.isArray(parsed?.top3) ? parsed.top3 : [];
  let rank = 0;
  for (const t of top3) {
    const idx = clamp(t);
    if (idx < 0 || seen.has(idx)) continue;
    rank += 1;
    seen.add(idx);
    out.push({ label: rank === 1 ? 'best' : `pick${rank}`, base64: images[idx].base64Data, mimeType: 'image/jpeg' });
  }

  // Backwards compat: if Gemini returned old format with bestFrame instead of top3
  if (!top3.length) {
    const bestIdx = clamp(parsed?.bestFrame);
    if (bestIdx >= 0) { out.push({ label: 'best', base64: images[bestIdx].base64Data, mimeType: 'image/jpeg' }); seen.add(bestIdx); }
  }

  // faceFrame (if not already in top3)
  const faceIdx = clamp(parsed?.faceFrame);
  if (faceIdx >= 0 && !seen.has(faceIdx)) { out.push({ label: 'face', base64: images[faceIdx].base64Data, mimeType: 'image/jpeg' }); seen.add(faceIdx); }

  // outfitFrames
  const outfitList = Array.isArray(parsed?.outfitFrames) ? parsed.outfitFrames : [];
  let n = 0;
  for (const oi of outfitList) {
    const idx = clamp(oi);
    if (idx < 0 || seen.has(idx)) continue;
    seen.add(idx); n += 1;
    out.push({ label: outfitList.length > 1 ? `outfit${n}` : 'outfit', base64: images[idx].base64Data, mimeType: 'image/jpeg' });
  }

  // Fallback: model gave nothing usable → return the middle candidate
  if (!out.length) {
    const mid = Math.floor(images.length / 2);
    out.push({ label: 'frame', base64: images[mid].base64Data, mimeType: 'image/jpeg' });
  }
  log.info('smart_frames_done', { candidates: images.length, returned: out.length, top3: top3.slice(0, 3), faceIdx });
  return out;
}

// POST /api/instagram-frames/extract-smart-from-upload?type=video/mp4
// Body: raw video bytes. "Smart" mode for a dropped/uploaded video file.
router.post('/extract-smart-from-upload', express.raw({ type: 'application/octet-stream', limit: '300mb' }), async (req, res, next) => {
  const sessionDir = path.join(getTempDir(), crypto.randomUUID());
  try {
    const buf = req.body;
    if (!Buffer.isBuffer(buf) || buf.length === 0) throw new AppError('No video data received', 400, 'VALIDATION_ERROR');
    const t = String(req.query.type || '');
    const ext = /webm/i.test(t) ? '.webm' : /(quicktime|mov)/i.test(t) ? '.mov' : /(m4v|mp4)/i.test(t) ? '.mp4' : '.mp4';
    fs.mkdirSync(sessionDir, { recursive: true });
    const videoPath = path.join(sessionDir, `upload${ext}`);
    fs.writeFileSync(videoPath, buf);
    const frames = await smartPickFrames(videoPath, sessionDir);
    res.json({ success: true, data: { frames } });
  } catch (err) {
    next(err);
  } finally {
    cleanupDir(sessionDir);
  }
});

// POST /api/instagram-frames/extract-smart-from-media   Body: { mediaUrl }
// "Smart" mode for the link import: download a public CDN video url and pick face + outfit frames.
router.post('/extract-smart-from-media', async (req, res, next) => {
  const sessionDir = path.join(getTempDir(), crypto.randomUUID());
  try {
    const { mediaUrl } = req.body || {};
    if (!mediaUrl || typeof mediaUrl !== 'string' || !mediaUrl.startsWith('http')) {
      throw new AppError('"mediaUrl" is required', 400, 'VALIDATION_ERROR');
    }
    fs.mkdirSync(sessionDir, { recursive: true });
    const axios = require('axios');
    const resp = await axios.get(mediaUrl, { responseType: 'arraybuffer', timeout: 120_000 });
    const videoPath = path.join(sessionDir, 'media.mp4');
    fs.writeFileSync(videoPath, Buffer.from(resp.data));
    const frames = await smartPickFrames(videoPath, sessionDir);
    res.json({ success: true, data: { frames } });
  } catch (err) {
    if (err.response) return next(new AppError(`Could not download media (${err.response.status}).`, 502, 'MEDIA_DOWNLOAD_FAILED'));
    next(err);
  } finally {
    cleanupDir(sessionDir);
  }
});

// POST /api/instagram-frames/extract
router.post('/extract', async (req, res, next) => {
  const sessionDir = path.join(getTempDir(), crypto.randomUUID());

  try {
    const { url, frameCount = 10, intervalMs = 200, smartPick = false, smart = false } = req.body;

    if (!url || typeof url !== 'string') {
      throw new AppError('"url" is required', 400, 'VALIDATION_ERROR');
    }

    const platform = detectPlatform(url);
    if (!platform) {
      throw new AppError('URL must be a valid Instagram, TikTok, or X (Twitter) post/video link', 400, 'VALIDATION_ERROR');
    }

    let cookiesPath;
    let platformName;
    if (platform === 'tiktok') {
      cookiesPath = TT_COOKIES_PATH;
      platformName = 'TikTok';
    } else if (platform === 'x') {
      cookiesPath = X_COOKIES_PATH;
      platformName = 'X (Twitter)';
    } else {
      cookiesPath = IG_COOKIES_PATH;
      platformName = 'Instagram';
    }

    // Cookies are REQUIRED
    if (!fs.existsSync(cookiesPath)) {
      throw new AppError(
        `${platformName} requires cookies to download. Please set up your cookies.txt first.`,
        401,
        'NO_COOKIES'
      );
    }

    const count = Math.max(1, Math.min(MAX_FRAMES, Math.round(Number(frameCount) || 10)));
    const interval = Math.max(MIN_INTERVAL_MS, Math.min(MAX_INTERVAL_MS, Math.round(Number(intervalMs) || 200)));

    fs.mkdirSync(sessionDir, { recursive: true });
    const videoOutputTemplate = path.join(sessionDir, 'video.%(ext)s');

    const ytDlp = findYtDlp();
    const scraperProxy = resolveScraperProxy();
    log.info('media_frames_download_start', { platform, url, count, interval, proxy: scraperProxy ? 'yes' : 'no' });

    let fallbackToGalleryDl = false;
    let dlErrMessage = '';

    try {
      const ytArgs = [
        '--no-playlist',
        '--cookies', cookiesPath,
        '--impersonate', 'chrome',
        '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        '--output', videoOutputTemplate,
        '--no-warnings',
        '--quiet',
      ];
      if (scraperProxy) ytArgs.push('--proxy', scraperProxy);
      ytArgs.push(url);
      await execFileAsync(ytDlp, ytArgs, { timeout: 90_000 });
    } catch (dlErr) {
      dlErrMessage = dlErr.stderr || dlErr.message || '';
      log.warn('media_frames_yt_dlp_failed', { platform, error: dlErrMessage });
      fallbackToGalleryDl = true;
    }

    if (fallbackToGalleryDl) {
      log.info('media_frames_fallback_gallery_dl', { platform, url });
      const galleryDl = findGalleryDl();
      try {
        const gdlArgs = ['--cookies', cookiesPath, '--directory', sessionDir];
        if (scraperProxy) gdlArgs.push('--proxy', scraperProxy);
        gdlArgs.push(url);
        await execFileAsync(galleryDl, gdlArgs, { timeout: 60_000 });
      } catch (gdlErr) {
        log.warn('media_frames_gallery_dl_failed', { platform, error: gdlErr.stderr || gdlErr.message });

        // Last resort (Instagram only): Apify uses its own token, so it can rescue
        // cookie-expired / private / IP-blocked failures that the local tools can't.
        let apifyOk = false;
        if (platform === 'instagram') {
          try {
            apifyOk = await tryApifyImageFallback(url, sessionDir);
          } catch (apErr) {
            log.warn('media_frames_apify_fallback_failed', { error: apErr.message });
          }
        }

        if (!apifyOk) {
          const msg = gdlErr.stderr || gdlErr.message || '';
          const lowerMsg = msg.toLowerCase();

          let detail = `Make sure the URL is a valid public ${platformName} post or video.`;
          if (
            lowerMsg.includes('login') || lowerMsg.includes('sign in') || lowerMsg.includes('private') ||
            dlErrMessage.toLowerCase().includes('login') || dlErrMessage.toLowerCase().includes('sign in')
          ) {
            throw new AppError(
              `${platformName} rejected the cookies or it is a private post. Please export fresh cookies and save them again.`,
              401,
              'COOKIES_EXPIRED'
            );
          } else if (lowerMsg.includes('empty media response') || dlErrMessage.toLowerCase().includes('empty media response')) {
            detail = `${platformName} sent an empty media response. The post might be restricted, age-gated, or private.`;
          } else if (lowerMsg.includes('400') || dlErrMessage.toLowerCase().includes('400')) {
            detail = `${platformName} API returned 400 Bad Request. Scraper might be temporarily blocked or rate-limited.`;
          } else if (lowerMsg.includes('403') || dlErrMessage.toLowerCase().includes('403')) {
            detail = `${platformName} API returned 403 Forbidden. Your IP or cookies might be blocked.`;
          }

          throw new AppError(
            `Could not download this ${platformName} post. ${detail}`,
            422,
            'DOWNLOAD_FAILED'
          );
        }
        log.info('media_frames_apify_fallback_ok', { url });
      }
    }

    // Now check what files we got. yt-dlp writes "video.*"; gallery-dl uses its OWN names,
    // so also treat any video-extension file (from either tool) as the clip to frame.
    // Otherwise a reel that gallery-dl downloaded falls through to the image branch below
    // and we'd return its ▶ cover thumbnail instead of a real frame. Largest file first
    // (the real video, not a tiny cover/sidecar sibling).
    const VIDEO_EXTS = ['.mp4', '.mkv', '.webm', '.mov', '.m4v', '.avi'];
    const videoFiles = fs.readdirSync(sessionDir)
      .filter(f => f.startsWith('video.') || VIDEO_EXTS.includes(path.extname(f).toLowerCase()))
      .map(f => { let size = 0; try { size = fs.statSync(path.join(sessionDir, f)).size; } catch { /* ignore */ } return { f, size }; })
      .sort((a, b) => b.size - a.size)
      .map(x => x.f);
    let frames = [];

    if (videoFiles.length > 0) {
      // Find the downloaded file (yt-dlp fills in the extension)
      const actualVideo = path.join(sessionDir, videoFiles[0]);

      // Smart mode OR smartPick: use AI vision picker for best face + outfit frames
      if (smart || smartPick) {
        try {
          const smartFrames = await smartPickFrames(actualVideo, sessionDir);
          log.info('media_frames_done', { platform, url, frames: smartFrames.length, mode: 'smart' });
          return res.json({ success: true, data: { frames: smartFrames.map((sf, idx) => ({ index: idx, timestampMs: 0, ...sf })), frameCount: smartFrames.length } });
        } catch (smartErr) {
          // If smart picker fails (e.g. API key issue), fall through to basic extraction
          log.warn('smart_pick_fallback', { error: smartErr.message });
        }
      }

      // Extract frames with ffmpeg
      const framesDir = path.join(sessionDir, 'frames');
      fs.mkdirSync(framesDir, { recursive: true });

      const fpsValue = (1000 / interval).toFixed(4); // e.g. 200ms → 5fps
      const framePattern = path.join(framesDir, 'frame_%03d.jpg');

      try {
        if (smartPick) {
          // Smart single-frame pick: ffmpeg's `thumbnail` filter scans across the clip and
          // returns the most *representative* frame — it deliberately skips black/blurry/
          // transition frames (the intro moments that catch a partial body). No ML needed.
          // A large batch (n) covers the whole short reel in one pass.
          await execFileAsync(ffmpegPath, [
            '-i', actualVideo,
            '-vf', 'thumbnail=n=500',
            '-frames:v', '1',
            '-q:v', '2',
            path.join(framesDir, 'frame_001.jpg'),
          ], { timeout: 45_000 });
        } else {
          await execFileAsync(ffmpegPath, [
            '-i', actualVideo,
            '-vf', `fps=${fpsValue}`,
            '-frames:v', String(count),
            '-q:v', '3',
            framePattern,
          ], { timeout: 30_000 });
        }
      } catch (ffErr) {
        log.warn('ig_frames_ffmpeg_failed', { error: ffErr.message });
        throw new AppError('Frame extraction failed — the video may be in an unsupported format.', 422, 'FFMPEG_FAILED');
      }

      const frameFiles = fs.readdirSync(framesDir).filter(f => f.endsWith('.jpg')).sort();
      if (!frameFiles.length) {
        throw new AppError('No frames could be extracted from this video', 422, 'NO_FRAMES');
      }

      frames = frameFiles.map((file, idx) => {
        const buf = fs.readFileSync(path.join(framesDir, file));
        return {
          index: idx,
          timestampMs: Math.round(idx * interval),
          base64: buf.toString('base64'),
          mimeType: 'image/jpeg',
        };
      });
    } else {
      // Succeeded via gallery-dl fallback (static photo/carousel images)
      const imageExtensions = ['.jpg', '.jpeg', '.png', '.webp'];
      const imageFiles = fs.readdirSync(sessionDir)
        .filter(f => {
          const ext = path.extname(f).toLowerCase();
          return imageExtensions.includes(ext);
        })
        .sort(); // preserve carousel index order

      if (!imageFiles.length) {
        throw new AppError('No images could be extracted from this post.', 422, 'DOWNLOAD_EMPTY');
      }

      frames = imageFiles.map((file, idx) => {
        const buf = fs.readFileSync(path.join(sessionDir, file));
        const ext = path.extname(file).toLowerCase();
        const mimeType = ext === '.png' ? 'image/png' : ext === '.webp' ? 'image/webp' : 'image/jpeg';
        return {
          index: idx,
          timestampMs: 0,
          base64: buf.toString('base64'),
          mimeType,
        };
      });
    }

    log.info('media_frames_done', { platform, url, frames: frames.length });
    res.json({ success: true, data: { frames, frameCount: frames.length, intervalMs: interval } });
  } catch (err) {
    next(err);
  } finally {
    cleanupDir(sessionDir);
  }
});

// Download the FULL source reel/video (not a frame) for a given post URL. Re-downloads on demand
// via the same yt-dlp -> gallery-dl flow used for framing, then streams the mp4 back as an attachment.
router.post('/download-video', async (req, res, next) => {
  const sessionDir = path.join(getTempDir(), crypto.randomUUID());
  try {
    const { url } = req.body || {};
    if (!url || typeof url !== 'string') throw new AppError('"url" is required', 400, 'VALIDATION_ERROR');

    const platform = detectPlatform(url);
    if (!platform) throw new AppError('URL must be a valid Instagram, TikTok, or X (Twitter) link', 400, 'VALIDATION_ERROR');

    let cookiesPath;
    let platformName;
    if (platform === 'tiktok') { cookiesPath = TT_COOKIES_PATH; platformName = 'TikTok'; }
    else if (platform === 'x') { cookiesPath = X_COOKIES_PATH; platformName = 'X (Twitter)'; }
    else { cookiesPath = IG_COOKIES_PATH; platformName = 'Instagram'; }

    if (!fs.existsSync(cookiesPath)) {
      throw new AppError(`${platformName} requires cookies to download. Set up your cookies.txt first.`, 401, 'NO_COOKIES');
    }

    fs.mkdirSync(sessionDir, { recursive: true });
    const videoOutputTemplate = path.join(sessionDir, 'video.%(ext)s');
    const ytDlp = findYtDlp();
    const scraperProxy = resolveScraperProxy();
    log.info('download_video_start', { platform, url, proxy: scraperProxy ? 'yes' : 'no' });

    let fallbackToGalleryDl = false;
    try {
      const ytArgs = [
        '--no-playlist', '--cookies', cookiesPath, '--impersonate', 'chrome',
        '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        '--output', videoOutputTemplate, '--no-warnings', '--quiet',
      ];
      if (scraperProxy) ytArgs.push('--proxy', scraperProxy);
      ytArgs.push(url);
      await execFileAsync(ytDlp, ytArgs, { timeout: 120_000 });
    } catch (dlErr) {
      log.warn('download_video_yt_dlp_failed', { platform, error: (dlErr.stderr || dlErr.message || '').slice(0, 200) });
      fallbackToGalleryDl = true;
    }

    if (fallbackToGalleryDl) {
      const galleryDl = findGalleryDl();
      try {
        const gdlArgs = ['--cookies', cookiesPath, '--directory', sessionDir];
        if (scraperProxy) gdlArgs.push('--proxy', scraperProxy);
        gdlArgs.push(url);
        await execFileAsync(galleryDl, gdlArgs, { timeout: 90_000 });
      } catch (gdlErr) {
        const msg = (gdlErr.stderr || gdlErr.message || '').toLowerCase();
        if (msg.includes('login') || msg.includes('sign in') || msg.includes('private')) {
          throw new AppError(`${platformName} rejected the cookies or the post is private. Export fresh cookies and save them again.`, 401, 'COOKIES_EXPIRED');
        }
        throw new AppError(`Could not download this ${platformName} video. It may be private, age-gated, or removed.`, 422, 'DOWNLOAD_FAILED');
      }
    }

    const VIDEO_EXTS = ['.mp4', '.mkv', '.webm', '.mov', '.m4v', '.avi'];
    const videoFiles = fs.readdirSync(sessionDir)
      .filter((f) => f.startsWith('video.') || VIDEO_EXTS.includes(path.extname(f).toLowerCase()))
      .map((f) => { let size = 0; try { size = fs.statSync(path.join(sessionDir, f)).size; } catch { /* ignore */ } return { f, size }; })
      .sort((a, b) => b.size - a.size);

    if (!videoFiles.length) {
      throw new AppError('No video found at that link — it may be a photo-only post.', 422, 'NO_VIDEO');
    }

    const best = videoFiles[0].f;
    const filePath = path.join(sessionDir, best);
    const ext = path.extname(best).toLowerCase() || '.mp4';
    const short = (url.match(/\/(?:reel|reels|p|tv|video)\/([A-Za-z0-9_-]+)/) || [])[1] || 'clip';
    const downloadName = `${platform}_${short}${ext}`;

    res.download(filePath, downloadName, (err) => {
      if (err) log.warn('download_video_send_failed', { error: err.message });
      cleanupDir(sessionDir);
    });
  } catch (err) {
    cleanupDir(sessionDir);
    next(err);
  }
});

// Kick a best-effort yt-dlp self-update shortly after boot (non-blocking, skipped in tests).
if (process.env.NODE_ENV !== 'test' && !process.env.VITEST) {
  setTimeout(runYtDlpSelfUpdate, 4000);
}

module.exports = router;
module.exports.runYtDlpSelfUpdate = runYtDlpSelfUpdate;
